### ISSUE TITLE
leanback launcher on linage 14.1

### ISSUE THREAD

**Issue by rajaa1996** [JJProductionsDK/android_device_brcm_rpi3#1]
u tell how to install leanback launcher in rpi3 on the linage 14.1 os from konsta 
i installed linage 14.1 and i dono how to modify the os to change the launcher can u tell how to modify it?

**Comment by JJakaJonas** [comment]
I don't remember if you can install gapps for Android TV on his build.
But you can try that.

**Comment by JJakaJonas** [comment]
No response...
Case closed
